spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: target/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory

  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    # url: jdbc:h2:mem:testdb
  batch:
    job:
      enabled: false
hapi:
  fhir:
    version: R4
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jpa
      server-version: 1.0.0
      implementation-description: Spring Boot Jpa Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      allow_cascading_deletes: true
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    jpa:
      scheduling-disabled: true
      subscription-enabled: false
management:
  security:
    enabled: false

app:
  redirect-uri: http://localhost:8080/auth
  npi.system: http://hl7.org/fhir/sid/us-npi
  payers:
    list:
      - name: Diamond Health
        auth-uri: https://auth.logicahealth.org/authorize
        token-uri: https://auth.logicahealth.org/token
        fhir-server-uri: https://api.logicahealth.org/DaVinciPDexProvider/data
        client-id: 7ae69b73-34ab-446f-b3dc-6dc958794576
        exclude-resources:
        scope: launch/patient patient/*.read
      - name: New Way Insurance
        auth-uri: https://auth.logicahealth.org/authorize
        token-uri: https://auth.logicahealth.org/token
        fhir-server-uri: https://api.logicahealth.org/PDEXPATIONTUIR4/data
        client-id: 706579ca-48b9-451f-b7e9-2de6a81cc8db
        exclude-resources: Practitioner
        scope: launch/patient patient/*.read
      - name: Premium
        auth-uri: https://auth.logicahealth.org/authorize
        token-uri: https://auth.logicahealth.org/token
        fhir-server-uri: https://api.logicahealth.org/DaVinciPDexProvider/data
        client-id: 7ae69b73-34ab-446f-b3dc-6dc958794576
        exclude-resources: MedicationDispense
        scope: launch/patient patient/*.read
      - name: Public Insurance
        auth-uri: https://auth.logicahealth.org/authorize
        token-uri: https://auth.logicahealth.org/token
        fhir-server-uri: https://api.logicahealth.org/DaVinciPDexProvider/data
        client-id: 7ae69b73-34ab-446f-b3dc-6dc958794576
        exclude-resources: MedicationDispense
        scope: launch/patient patient/*.read
      - name: Insurre
        auth-uri: https://auth.logicahealth.org/authorize
        token-uri: https://auth.logicahealth.org/token
        fhir-server-uri: https://api.logicahealth.org/DaVinciPDexProvider/data
        client-id: 7ae69b73-34ab-446f-b3dc-6dc958794576
        exclude-resources: MedicationDispense
        scope: launch/patient patient/*.read